# Generated by Django 4.1.5 on 2023-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment_list',
            field=models.TextField(null=True, verbose_name='첨부파일 이름 리스트'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(null=True, verbose_name='게시물 HTML'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(null=True, verbose_name='게시물 발행일(작성일자)'),
        ),
    ]
