# Generated by Django 4.1.5 on 2023-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='게시물 HTML'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, verbose_name='게시물 URL'),
        ),
    ]
